// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwfZjdiQSzUGuXBUkCrLssn6CbGowKmPA',
    appId: '1:68022749444:web:e16731e7124b4f25f22851',
    messagingSenderId: '68022749444',
    projectId: 'auto-battler-6593d',
    authDomain: 'auto-battler-6593d.firebaseapp.com',
    storageBucket: 'auto-battler-6593d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOAVunXD6BGW8V_4OjAX5lf44koLr8X7o',
    appId: '1:68022749444:android:71a5034d79e1d627f22851',
    messagingSenderId: '68022749444',
    projectId: 'auto-battler-6593d',
    storageBucket: 'auto-battler-6593d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79RwCoDnVNCTmwb6PsfoHB-L9r_iQq_Q',
    appId: '1:68022749444:ios:e015d48d165cf12df22851',
    messagingSenderId: '68022749444',
    projectId: 'auto-battler-6593d',
    storageBucket: 'auto-battler-6593d.appspot.com',
    iosClientId: '68022749444-2rbjdq8tcuip5bugpie4kmgv92bunh1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoBattler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB79RwCoDnVNCTmwb6PsfoHB-L9r_iQq_Q',
    appId: '1:68022749444:ios:e015d48d165cf12df22851',
    messagingSenderId: '68022749444',
    projectId: 'auto-battler-6593d',
    storageBucket: 'auto-battler-6593d.appspot.com',
    iosClientId: '68022749444-2rbjdq8tcuip5bugpie4kmgv92bunh1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoBattler',
  );
}
